-- EMPLOUEES (SCOTT의 EMP통일개념) // EMP보다 크다
-- FRIST_NAME, LAST_NAME, JOB_ID 조회
SELECT
	E.FIRST_NAME,
	E.LAST_NAME,
	E.JOB_ID
FROM
	EMPLOYEES e; 

-- job_id 중복 제외
SELECT
	DISTINCT E.JOB_ID
FROM
	EMPLOYEES e 
	
-- 사번이 176인 사원의 LAST_NAME과 부서번호 조회
SELECT
	E.LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	E.EMPLOYEE_ID = 176

-- 급여가 12000이상되는 사원의 LASE_NAME과 급여율 조회
	SELECT
	E.LAST_NAME,
	E.SALARY
FROM
	EMPLOYEES e
WHERE
	E.SALARY >= 12000 ;
-- 급여가 5000 ~ 12000 범위가 아닌 사원의 LAST_NAME과 급여율 조회
SELECT
	E.LAST_NAME,
	E.SALARY
FROM
	EMPLOYEES e
WHERE
	E.SALARY NOT BETWEEN 5000 AND 20000


SELECT
	E.LAST_NAME,
	E.SALARY
FROM
	EMPLOYEES e
WHERE
	E.SALARY >12000
	OR E.SALARY < 5000;


-- IN 
-- 20, 50번 부서에 근무하는 사원 조회(LAST_NAME, 부서번호), LAST_NAME 오름차순
SELECT
	E.LAST_NAME,
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	E.DEPARTMENT_ID IN (20, 50)
ORDER BY
	E.LAST_NAME ASC

-- SALARY가 2500, 3500, 7000 이며, JOB이 SA_REP, ST_CLERK가 아닌 사원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	E.SALARY NOT IN (2500, 3500, 7000)
	AND E.JOB_ID NOT IN ('SA_REP', 'ST_CLERK')
	
-- 날짜 데이터 '' 사용
-- 고용일이 2014년 사원 조회(2014-01-01 ~ 2014-12-31)
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	E.HIRE_DATE >= '2014-01-01'
	AND E.HIRE_DATE <= '2014-12-31'

SELECT *
FROM EMPLOYEES e 
WHERE E.HIRE_DATE BETWEEN '2014-01-01' AND '2014-12-31'

-- LIKE
-- LAST_NAME에 u가 포함되는 사원들의 사번, LAST_NAME조회
SELECT
	E.EMPLOYEE_ID,
	E.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE ('%u%')

-- LAST_NAME 의 4번째 글자가 A인 사원 들의 사번, LAST_NAME 조회
SELECT
	E.EMPLOYEE_ID,
	E.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE ('___a%')

-- LAST_NAME에 A 혹은 E글자가 있는 사원들의 사번, LAST_NAME 조회(LAST_NAME) 내림차순	
SELECT
	e.EMPLOYEE_ID ,
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE ('%a%')
	OR e.LAST_NAME LIKE('%e%')
ORDER BY
	e.LAST_NAME DESC

-- LAST_NAME에 A 와 E글자가 있는 사원들의 사번, LAST_NAME 조회(LAST_NAME) 내림차순	
SELECT
	e.EMPLOYEE_ID ,
	e.LAST_NAME
FROM
	EMPLOYEES e
WHERE
	e.LAST_NAME LIKE ('%a%')
	and e.LAST_NAME LIKE('%e%')
ORDER BY
	e.LAST_NAME DESC
	
-- IS NULL 
-- 매니저가 없는 사원들의 LAST_NAME, JOB_ID 조회
SELECT
	E.LAST_NAME, E.JOB_ID
FROM
	EMPLOYEES e
WHERE
	E.MANAGER_ID IS NULL
	
-- ST_CLERK인 직업을 가진 사원이 없는 부서 번호 조회(단, 부서번호가 널 값인 부서 제외)
SELECT DISTINCT
	E.DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	E.JOB_ID != 'ST_CLERK'
	AND E.DEPARTMENT_ID IS NOT NULL

-- COMMISSION_PCT가 NULL 이 아닌 사원들 중에서 COMMISSION=SALARY * COMMISSION=_PCT 를 구한다
-- 계산결과와 함께 사번, FRIST_NAME, JOB_ID 출력

SELECT
	E.EMPLOYEE_ID,
	E.FIRST_NAME,
	E.JOB_ID,
	E.SALARY  * E.COMMISSION_PCT "COMMISSION"
FROM
	EMPLOYEES e
WHERE
	E.COMMISSION_PCT IS NOT NULL 